# Generated by Django 4.1.7 on 2023-03-14 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0001_initial"),
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="country.country"
            ),
        ),
        migrations.DeleteModel(
            name="Country",
        ),
    ]
