# Generated by Django 4.1.7 on 2023-03-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
        ("clinic", "0003_clinic_doctor_in_charge_clinic_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinic",
            name="list_of_services",
        ),
        migrations.AddField(
            model_name="clinic",
            name="list_of_services",
            field=models.ManyToManyField(blank=True, to="service.service"),
        ),
    ]
