# Generated by Django 4.1.7 on 2023-03-14 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0002_county_subcounty"),
        ("clinic", "0004_remove_clinic_list_of_services_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="county",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="country.county"
            ),
        ),
        migrations.AlterField(
            model_name="clinic",
            name="sub_county",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="country.subcounty"
            ),
        ),
    ]
